In [2]:
from os import listdir
from os.path import isfile, join
import pandas as pd

In [48]:
path_base_original_real="C:\dataset\original_dataset\\real"
path_base_original_fake="C:\dataset\original_dataset\\fake"
fullpath_fake=path_base_original_fake+"\\fake.csv"
path_base_modified="C:\dataset\processed_datatset"
fullpath_modified=path_base_modified+"\\total_dataset.csv"
originaldataset_real = [f for f in listdir(path_base_original_real) if isfile(join(path_base_original_real, f))]
print(originaldataset_real)

originaldataset_fake = [f for f in listdir(path_base_original_fake) if isfile(join(path_base_original_fake, f))]
print(originaldataset_fake)

['articles1.csv', 'articles2.csv', 'articles3.csv']
['fake.csv']

<!-- # for i in originaldataset:
    fullpath=path_base_original+"\\"+i
    df=pd.read_csv(fullpath)
    delete_cols=["url","id","publication","author","date","year","month"]
    df.drop(delete_cols,axis=True,inplace=True)
    fullpath_modified=path_base_modified+"\\"+ i.split(".")[0]+"0.csv"
    df.to_csv(fullpath_modified,index=False,encoding="utf8")    
     -->

In [49]:
# 0--fake
# 1--real
l=list()
for i in originaldataset_real:
    fullpath_real=path_base_original_real+"\\"+i
    df=pd.read_csv(fullpath_real,usecols=[2,9])
    df["label"]=1
    print(df.head(5))
    l.append(df)
    
    
df=pd.read_csv(fullpath_fake,usecols=[4,5])
df.rename(columns=({'text':'content'}),  inplace=True )
df["label"]=0
print(df.head(5))
l.append(df)
df= pd.concat(l)
print(df.head(5))
print(df.shape)
df.to_csv(fullpath_modified,index=False,encoding="utf8")

                                               title  \
0  House Republicans Fret About Winning Their Hea...
1  Rift Between Officers and Residents as Killing...
2  Tyrus Wong, ‘Bambi’ Artist Thwarted by Racial ...
3  Among Deaths in 2016, a Heavy Toll in Pop Musi...
4  Kim Jong-un Says North Korea Is Preparing to T...

                                             content  label
0  WASHINGTON  —   Congressional Republicans have...      1
1  After the bullet shells get counted, the blood...      1
2  When Walt Disney’s “Bambi” opened in 1942, cri...      1
3  Death may be the great equalizer, but it isn’t...      1
4  SEOUL, South Korea  —   North Korea’s leader, ...      1
                                               title  \
0  Patriots Day Is Best When It Digs Past the Her...
1  A Break in the Search for the Origin of Comple...
2         Obama’s Ingenious Mention of Atticus Finch
3         Donald Trump Meets, and Assails, the Press
4               Trump: ’I Think’ Hacking Was Russian

                                             content  label
0  Patriots Day, Peter Berg’s new thriller that r...      1
1  In Norse mythology, humans and our world were ...      1
2  “If our democracy is to work in this increasin...      1
3  Updated on January 11 at 5:05 p. m. In his fir...      1
4  Updated at 12:25 p. m. After months of equivoc...      1
                                               title  \
0  Alton Sterling’s son: ’Everyone needs to prote...
1  Shakespeare’s first four folios sell at auctio...
2  My grandmother’s death saved me from a life of...
3  I feared my life lacked meaning. Cancer pushed...
4  Texas man serving life sentence innocent of do...

                                             content  label
0  The son of a Louisiana man whose father was sh...      1
1  Copies of William Shakespeare’s first four boo...      1
2  Debt: $20, 000, Source: College, credit cards,...      1
3  It was late. I was drunk, nearing my 35th birt...      1
4  A central Texas man serving a life sentence fo...      1
                                               title  \
0  Muslims BUSTED: They Stole Millions In Gov’t B...
1  Re: Why Did Attorney General Loretta Lynch Ple...
2  BREAKING: Weiner Cooperating With FBI On Hilla...
3  PIN DROP SPEECH BY FATHER OF DAUGHTER Kidnappe...
4  FANTASTIC! TRUMP'S 7 POINT PLAN To Reform Heal...

                                             content  label
0  Print They should pay all the back all the mon...      0
1  Why Did Attorney General Loretta Lynch Plead T...      0
2  Red State : \nFox News Sunday reported this mo...      0
3  Email Kayla Mueller was a prisoner and torture...      0
4  Email HEALTHCARE REFORM TO MAKE AMERICA GREAT ...      0
                                               title  \
0  House Republicans Fret About Winning Their Hea...
1  Rift Between Officers and Residents as Killing...
2  Tyrus Wong, ‘Bambi’ Artist Thwarted by Racial ...
3  Among Deaths in 2016, a Heavy Toll in Pop Musi...
4  Kim Jong-un Says North Korea Is Preparing to T...

                                             content  label
0  WASHINGTON  —   Congressional Republicans have...      1
1  After the bullet shells get counted, the blood...      1
2  When Walt Disney’s “Bambi” opened in 1942, cri...      1
3  Death may be the great equalizer, but it isn’t...      1
4  SEOUL, South Korea  —   North Korea’s leader, ...      1
(155569, 3)

In [50]:
print(df.tail(5))

      title                                            content  label
12994   NaN  It DOES allow you to put a dog face on top of ...      0
12995   NaN  Wait till you see what happens to the valuatio...      0
12996   NaN  I'm waiting for the one that puts a pussy on m...      0
12997   NaN  $4 Billion even after they are known to be kee...      0
12998   NaN  of course - how else would they disceminate te...      0

In [51]:
df.shape

(155569, 3)

In [52]:
bool_have_null =pd.isnull(df['content'])
df[bool_have_null]
# bool_have_null =pd.isnull(df['content'])
# df[bool_have_null]


#  df.dropna(subset=['title','content'], inplace=True)

                                                  title content  label
5555  Sur Twitter, Donald Trump se félicite d’avoir ...     NaN      0
5556    Live Soirée présidentielle US 2016 >> Le Gorafi     NaN      0
5557  Elections US : les premières estimations donne...     NaN      0
5558  Les Américains ne sont plus qu’à quelques heur...     NaN      0
5559               Donald Trump en 5 dates >> Le Gorafi     NaN      0
5560  Donald Trump s’excuse pour toutes les minorité...     NaN      0
5561            Hillary Clinton en 5 dates >> Le Gorafi     NaN      0
5562  Des millions d’Américains recherchent massivem...     NaN      0
5563  Les gardes-frontières se mettent en alerte pou...     NaN      0
5564  La Russie a profité de l’élection américaine p...     NaN      0
5565  New-York – Le lâcher de confettis prévu à Time...     NaN      0
5566  GuinessBook : 100 millions d’Américains batten...     NaN      0
5567  Vladimir Poutine est élu 45e Président des Eta...     NaN      0
5568  La Corée du Nord annonce avoir envoyé un missi...     NaN      0
5569  Heureux et souriant, il a la chance de toujour...     NaN      0
5570  Une fan demande le remboursement de son tatoua...     NaN      0
5571  Elle met en fuite un braqueur en lui jetant de...     NaN      0
5572  110% des Américains assurent qu’ils continuero...     NaN      0
5573  La sortie du dernier livre inédit du Gorafi éc...     NaN      0
5574  Il saoule tout le monde avec son analyse polit...     NaN      0
5575         Horoscope du 14 novembre 2016 >> Le Gorafi     NaN      0
5576  Grand-Prix du Brésil – Romain Grosjean obtient...     NaN      0
5577  SPA : Enfermé depuis trois jours dans une cage...     NaN      0
5578  #NDDL: Pour fêter l’autorisation des travaux, ...     NaN      0
5579  [Vidéo] Découvrez le Gorafi de l’Année 2017 >>...     NaN      0
5580  Trop essoufflé après avoir cherché ses affaire...     NaN      0
5581  La Trump Tower cambriolée – les voleurs seraie...     NaN      0
5582  «Pourquoi je suis candidat à la présidentielle...     NaN      0
5583  Pour booster les ventes, Dassault offre un por...     NaN      0
5584  Débat Primaire de la Droite : les Français pas...     NaN      0
5585  Des traces de vin rouge détectées dans le Beau...     NaN      0
5586  Ne supportant plus l’ambiance de la campagne é...     NaN      0
5587  Gorafi Magazine : Entretien exclusif avec Bara...     NaN      0
5588  Primaire – François Fillon se désiste au profi...     NaN      0
5589         Horoscope du 21 novembre 2016 >> Le Gorafi     NaN      0
5590  “Notre batal a coulé” par l’homme qui fait des...     NaN      0
5591  Après le succès de « Mariés au premier regard ...     NaN      0
5592  Il se fait cryogéniser dans l’espoir de voir u...     NaN      0
5593  Le top des recherches Google passe en top des ...     NaN      0
5594  Révélations – François Fillon serait de droite...     NaN      0
5595  Vendée Globe – Un skipper fait demi-tour après...     NaN      0
5596  La voyante lisait l’avenir dans les cartes ble...     NaN      0
5597  Nous avons comparé les programmes d’Alain Jupp...     NaN      0
5598  [Vidéo] Que trouve-t-on dans « Le Gorafi de l’...     NaN      0
5599  Gorafi Magazine: Barack Obama « Je vous ai déj...     NaN      0
5600  « J’y crois encore ! » par Alain Juppé en trai...     NaN      0

In [53]:
len(df[bool_have_null])
# df.shape

46

In [56]:
bool_have_null =pd.isnull(df['title'])
df[bool_have_null]
# len(df[bool_have_null])

      title                                            content  label
14875   NaN  Harry Reid tries to drop kick Alan Grayson rig...      1
20638   NaN  The occupiers, who took over buildings at the ...      1
60      NaN  So ,you have Rothschild banksters and British ...      0
61      NaN  Here is the problem . The USA constitution sta...      0
62      NaN  There is plenty of proof the machines are rigg...      0
...     ...                                                ...    ...
12994   NaN  It DOES allow you to put a dog face on top of ...      0
12995   NaN  Wait till you see what happens to the valuatio...      0
12996   NaN  I'm waiting for the one that puts a pussy on m...      0
12997   NaN  $4 Billion even after they are known to be kee...      0
12998   NaN  of course - how else would they disceminate te...      0

[682 rows x 3 columns]

In [57]:
 df.dropna(subset=['title','content'], inplace=True)

In [58]:
df.shape

(154841, 3)

In [45]:


df[bool_have_null]

Empty DataFrame
Columns: [title, content, label]
Index: []

In [46]:
bool_have_null =pd.isnull(df['content'])
df[bool_have_null]

Empty DataFrame
Columns: [title, content, label]
Index: []

In [60]:
df.pivot_table(index=['label'],aggfunc='size')

label
0     12273
1    142568
dtype: int64